<?php

namespace Database\Seeders;

use App\Models\DVD;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Headphone;
use App\Models\Monitor;
use App\Models\Keyboard;
use App\Models\Penyimpanan;
use App\Models\Motherboard;
use App\Models\Mouse;
use App\Models\Processor;
use App\Models\PSU;
use App\Models\RAM;
use App\Models\User;
use App\Models\VGA;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // 1. FIRST: Seed roles and permissions
        $this->call([
            LaboratoriumSeeder::class,
            RolePermissionSeeder::class,
            UserSeeder::class,
        ]);

        $tahunSekarang = date('Y');

        Headphone::insert([
            [
                'no_inventaris' => 'LABKOM/HP/001/' . $tahunSekarang,
                'merk' => 'Logitech',
                'nama' => 'H111 Stereo Headset',
                'spesifikasi' => 'Stereo, Noise-canceling microphone, 3.5mm audio jack',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 30),
            ],
            [
                'no_inventaris' => 'LABKOM/HP/002/' . ($tahunSekarang - 1),
                'merk' => 'A4Tech',
                'nama' => 'HS-19 Stereo',
                'spesifikasi' => 'Stereo, Adjustable microphone, Comfortable earcups',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 30),
            ],
            [
                'no_inventaris' => 'LABKOM/HP/003/' . $tahunSekarang,
                'merk' => 'Rexus',
                'nama' => 'Vonix F22',
                'spesifikasi' => 'Gaming Headset, LED, 3.5mm jack',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 20),
            ],
            [
                'no_inventaris' => 'LABKOM/HP/004/' . ($tahunSekarang - 1),
                'merk' => 'Philips',
                'nama' => 'SHP2000',
                'spesifikasi' => 'Over-ear, Lightweight, 2m cable',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 30),
            ],
            [
                'no_inventaris' => 'LABKOM/HP/005/' . $tahunSekarang,
                'merk' => 'JBL',
                'nama' => 'C100SI (In-Ear)',
                'spesifikasi' => 'In-ear, Lightweight, JBL Pure Bass sound',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(15, 40),
            ],
            [
                'no_inventaris' => 'LABKOM/HP/006/' . ($tahunSekarang - 1),
                'merk' => 'Sony',
                'nama' => 'MDR-ZX110AP',
                'spesifikasi' => 'On-Ear, Foldable, Inline microphone',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 25),
            ],
            [
                'no_inventaris' => 'LABKOM/HP/007/' . $tahunSekarang,
                'merk' => 'Fantech',
                'nama' => 'HG15 Captain',
                'spesifikasi' => 'Gaming Headset, RGB, USB + 3.5mm jack',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 20),
            ],
            [
                'no_inventaris' => 'LABKOM/HP/008/' . ($tahunSekarang - 1),
                'merk' => 'Sennheiser',
                'nama' => 'PC 3 Chat',
                'spesifikasi' => 'Lightweight, Noise-canceling microphone, Stereo',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 15),
            ],
            [
                'no_inventaris' => 'LABKOM/HP/009/' . $tahunSekarang,
                'merk' => 'Edifier',
                'nama' => 'K800 USB',
                'spesifikasi' => 'USB Connector, Padded earcups, Microphone',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 20),
            ],
            [
                'no_inventaris' => 'LABKOM/HP/010/' . ($tahunSekarang - 1),
                'merk' => 'Genius',
                'nama' => 'HS-04SU',
                'spesifikasi' => 'Adjustable Headband, Noise-canceling mic, Stereo',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 30),
            ],
        ]);

        // Seeder Processors (Low-Mid End)
        Processor::insert([
            [
                'no_inventaris' => 'LABKOM/PR/001/' . $tahunSekarang,
                'merk' => 'Intel',
                'tipe' => 'Core i3-10100F',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 15),
            ],
            [
                'no_inventaris' => 'LABKOM/PR/002/' . ($tahunSekarang - 1),
                'merk' => 'AMD',
                'tipe' => 'Ryzen 3 3200G',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 15),
            ],
            [
                'no_inventaris' => 'LABKOM/PR/003/' . ($tahunSekarang - 2),
                'merk' => 'Intel',
                'tipe' => 'Pentium Gold G6400',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 20),
            ],
            [
                'no_inventaris' => 'LABKOM/PR/004/' . $tahunSekarang,
                'merk' => 'AMD',
                'tipe' => 'Athlon 3000G',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 20),
            ],
            [
                'no_inventaris' => 'LABKOM/PR/005/' . ($tahunSekarang - 1),
                'merk' => 'Intel',
                'tipe' => 'Core i5-10400F',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 12),
            ],
            [
                'no_inventaris' => 'LABKOM/PR/006/' . ($tahunSekarang - 2),
                'merk' => 'AMD',
                'tipe' => 'Ryzen 5 3400G',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 12),
            ],
            [
                'no_inventaris' => 'LABKOM/PR/007/' . $tahunSekarang,
                'merk' => 'Intel',
                'tipe' => 'Celeron G5905',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 25),
            ],
            [
                'no_inventaris' => 'LABKOM/PR/008/' . ($tahunSekarang - 1),
                'merk' => 'AMD',
                'tipe' => 'Ryzen 3 4300G',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 15),
            ],
            [
                'no_inventaris' => 'LABKOM/PR/009/' . ($tahunSekarang - 2),
                'merk' => 'Intel',
                'tipe' => 'Core i3-9100F',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 18),
            ],
            [
                'no_inventaris' => 'LABKOM/PR/010/' . $tahunSekarang,
                'merk' => 'AMD',
                'tipe' => 'Ryzen 5 5500',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(4, 10),
            ],
        ]);

        // Seeder VGA (Low-Mid End)
        VGA::insert([
            [
                'no_inventaris' => 'LABKOM/VGA/001/' . $tahunSekarang,
                'merk' => 'NVIDIA',
                'tipe' => 'GeForce GT 1030',
                'kapasitas' => 2,
                'spesifikasi' => 'GDDR5, 64-bit',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 20),
            ],
            [
                'no_inventaris' => 'LABKOM/VGA/002/' . ($tahunSekarang - 1),
                'merk' => 'AMD',
                'tipe' => 'Radeon RX 550',
                'kapasitas' => 4,
                'spesifikasi' => 'GDDR5, 128-bit',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 20),
            ],
            [
                'no_inventaris' => 'LABKOM/VGA/003/' . ($tahunSekarang - 2),
                'merk' => 'NVIDIA',
                'tipe' => 'GeForce GTX 1650',
                'kapasitas' => 4,
                'spesifikasi' => 'GDDR6, 128-bit',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 15),
            ],
            [
                'no_inventaris' => 'LABKOM/VGA/004/' . $tahunSekarang,
                'merk' => 'AMD',
                'tipe' => 'Radeon RX 570',
                'kapasitas' => 8,
                'spesifikasi' => 'GDDR5, 256-bit',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(4, 12),
            ],
            [
                'no_inventaris' => 'LABKOM/VGA/005/' . ($tahunSekarang - 1),
                'merk' => 'NVIDIA',
                'tipe' => 'GeForce GTX 1050 Ti',
                'kapasitas' => 4,
                'spesifikasi' => 'GDDR5, 128-bit',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 18),
            ],
            [
                'no_inventaris' => 'LABKOM/VGA/006/' . ($tahunSekarang - 2),
                'merk' => 'AMD',
                'tipe' => 'Radeon RX 6500 XT',
                'kapasitas' => 4,
                'spesifikasi' => 'GDDR6, 64-bit',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(3, 10),
            ],
            [
                'no_inventaris' => 'LABKOM/VGA/007/' . $tahunSekarang,
                'merk' => 'Intel', // Menggunakan Intel Iris Xe sebagai contoh integrated/low-end
                'tipe' => 'Iris Xe Graphics (Integrated)',
                'kapasitas' => 0, // Shared memory
                'spesifikasi' => 'Integrated with CPU',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 30), // Stok bisa tinggi jika ini bagian dari CPU
            ],
            [
                'no_inventaris' => 'LABKOM/VGA/008/' . ($tahunSekarang - 1),
                'merk' => 'NVIDIA',
                'tipe' => 'Quadro P400',
                'kapasitas' => 2,
                'spesifikasi' => 'GDDR5, Workstation Card',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(2, 8),
            ],
            [
                'no_inventaris' => 'LABKOM/VGA/009/' . ($tahunSekarang - 2),
                'merk' => 'AMD',
                'tipe' => 'Radeon Pro WX 2100',
                'kapasitas' => 2,
                'spesifikasi' => 'GDDR5, Workstation Card',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(2, 8),
            ],
            [
                'no_inventaris' => 'LABKOM/VGA/010/' . $tahunSekarang,
                'merk' => 'NVIDIA',
                'tipe' => 'GeForce GT 710',
                'kapasitas' => 2,
                'spesifikasi' => 'DDR3, 64-bit, Basic Display',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 25),
            ],
        ]);

        // Seeder RAM (Low-Mid End)
        RAM::insert([
            [
                'no_inventaris' => 'LABKOM/RAM/001/' . $tahunSekarang,
                'merk' => 'Kingston',
                'tipe' => 'DDR4',
                'kapasitas' => 8,
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 30),
            ],
            [
                'no_inventaris' => 'LABKOM/RAM/002/' . ($tahunSekarang - 1),
                'merk' => 'Corsair',
                'tipe' => 'DDR4',
                'kapasitas' => 16, // 2x8GB kit
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 20),
            ],
            [
                'no_inventaris' => 'LABKOM/RAM/003/' . ($tahunSekarang - 2),
                'merk' => 'Crucial',
                'tipe' => 'DDR3', // Older systems
                'kapasitas' => 4,
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 15),
            ],
            [
                'no_inventaris' => 'LABKOM/RAM/004/' . $tahunSekarang,
                'merk' => 'Samsung',
                'tipe' => 'DDR4',
                'kapasitas' => 8,
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 25),
            ],
            [
                'no_inventaris' => 'LABKOM/RAM/005/' . ($tahunSekarang - 1),
                'merk' => 'ADATA',
                'tipe' => 'DDR4',
                'kapasitas' => 16,
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 18),
            ],
            [
                'no_inventaris' => 'LABKOM/RAM/006/' . ($tahunSekarang - 2),
                'merk' => 'Team Group',
                'tipe' => 'DDR4',
                'kapasitas' => 8,
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 28),
            ],
            [
                'no_inventaris' => 'LABKOM/RAM/007/' . $tahunSekarang,
                'merk' => 'G.Skill',
                'tipe' => 'DDR4',
                'kapasitas' => 16, // 2x8GB
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(6, 15),
            ],
            [
                'no_inventaris' => 'LABKOM/RAM/008/' . ($tahunSekarang - 1),
                'merk' => 'Patriot',
                'tipe' => 'DDR3', // Older systems
                'kapasitas' => 8, // 2x4GB
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 12),
            ],
            [
                'no_inventaris' => 'LABKOM/RAM/009/' . ($tahunSekarang - 2),
                'merk' => 'Apacer',
                'tipe' => 'DDR4',
                'kapasitas' => 4,
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 20),
            ],
            [
                'no_inventaris' => 'LABKOM/RAM/010/' . $tahunSekarang,
                'merk' => 'V-Gen',
                'tipe' => 'DDR4',
                'kapasitas' => 8,
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(12, 30),
            ],
        ]);

        // Seeder Monitors (Low-Mid End)
        Monitor::insert([
            [
                'no_inventaris' => 'LABKOM/MN/001/' . $tahunSekarang,
                'merk' => 'LG',
                'nama' => '22MP410-B',
                'resolusi' => 1920, // 1920x1080
                'ukuran' => '21.5',
                'spesifikasi' => 'Full HD, IPS, AMD FreeSync',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 15),
            ],
            [
                'no_inventaris' => 'LABKOM/MN/002/' . ($tahunSekarang - 1),
                'merk' => 'Samsung',
                'nama' => 'S24R350FHE',
                'resolusi' => 1920,
                'ukuran' => '24',
                'spesifikasi' => 'Full HD, IPS, 75Hz',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 15),
            ],
            [
                'no_inventaris' => 'LABKOM/MN/003/' . ($tahunSekarang - 2),
                'merk' => 'Acer',
                'nama' => 'K202HQL Abi',
                'resolusi' => 1366, // 1366x768
                'ukuran' => '19.5',
                'spesifikasi' => 'HD+, TN Panel, VGA/HDMI',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 20),
            ],
            [
                'no_inventaris' => 'LABKOM/MN/004/' . $tahunSekarang,
                'merk' => 'Dell',
                'nama' => 'E2220H',
                'resolusi' => 1920,
                'ukuran' => '21.5',
                'spesifikasi' => 'Full HD, TN, VGA/DisplayPort',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(7, 14),
            ],
            [
                'no_inventaris' => 'LABKOM/MN/005/' . ($tahunSekarang - 1),
                'merk' => 'HP',
                'nama' => 'V214a',
                'resolusi' => 1920,
                'ukuran' => '20.7',
                'spesifikasi' => 'Full HD, TN, HDMI/VGA',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 18),
            ],
            [
                'no_inventaris' => 'LABKOM/MN/006/' . ($tahunSekarang - 2),
                'merk' => 'ViewSonic',
                'nama' => 'VA2246M-LED',
                'resolusi' => 1920,
                'ukuran' => '22',
                'spesifikasi' => 'Full HD, LED, DVI/VGA',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(6, 12),
            ],
            [
                'no_inventaris' => 'LABKOM/MN/007/' . $tahunSekarang,
                'merk' => 'BenQ',
                'nama' => 'GW2283',
                'resolusi' => 1920,
                'ukuran' => '21.5',
                'spesifikasi' => 'Full HD, IPS, Eye-care',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(7, 13),
            ],
            [
                'no_inventaris' => 'LABKOM/MN/008/' . ($tahunSekarang - 1),
                'merk' => 'Philips',
                'nama' => '221V8A',
                'resolusi' => 1920,
                'ukuran' => '21.5',
                'spesifikasi' => 'Full HD, VA, Adaptive Sync',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 16),
            ],
            [
                'no_inventaris' => 'LABKOM/MN/009/' . ($tahunSekarang - 2),
                'merk' => 'AOC',
                'nama' => 'E970SWN',
                'resolusi' => 1366,
                'ukuran' => '18.5',
                'spesifikasi' => 'HD, LED, VGA',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(12, 22),
            ],
            [
                'no_inventaris' => 'LABKOM/MN/010/' . $tahunSekarang,
                'merk' => 'Lenovo',
                'nama' => 'D22e-20',
                'resolusi' => 1920,
                'ukuran' => '21.45',
                'spesifikasi' => 'Full HD, VA, HDMI/VGA',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(9, 17),
            ],
        ]);

        // Seeder Keyboards (Low-Mid End)
        Keyboard::insert([
            [
                'no_inventaris' => 'LABKOM/KY/001/' . $tahunSekarang,
                'merk' => 'Logitech',
                'tipe' => 'K120 (USB)',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(15, 40),
            ],
            [
                'no_inventaris' => 'LABKOM/KY/002/' . ($tahunSekarang - 1),
                'merk' => 'Dell',
                'tipe' => 'KB216 (USB)',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(15, 40),
            ],
            [
                'no_inventaris' => 'LABKOM/KY/003/' . ($tahunSekarang - 2),
                'merk' => 'HP',
                'tipe' => 'K1500 (USB)',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 30),
            ],
            [
                'no_inventaris' => 'LABKOM/KY/004/' . $tahunSekarang,
                'merk' => 'A4Tech',
                'tipe' => 'KR-85 (USB)',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(12, 35),
            ],
            [
                'no_inventaris' => 'LABKOM/KY/005/' . ($tahunSekarang - 1),
                'merk' => 'Genius',
                'tipe' => 'KB-110X (USB)',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 25),
            ],
            [
                'no_inventaris' => 'LABKOM/KY/006/' . ($tahunSekarang - 2),
                'merk' => 'Logitech',
                'tipe' => 'MK220 (Wireless Combo)',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 20),
            ],
            [
                'no_inventaris' => 'LABKOM/KY/007/' . $tahunSekarang,
                'merk' => 'Fantech',
                'tipe' => 'K613 Fighter (Membrane Gaming)',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(7, 18),
            ],
            [
                'no_inventaris' => 'LABKOM/KY/008/' . ($tahunSekarang - 1),
                'merk' => 'Rexus',
                'tipe' => 'K1 Legionare (Membrane)',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(7, 18),
            ],
            [
                'no_inventaris' => 'LABKOM/KY/009/' . ($tahunSekarang - 2),
                'merk' => 'Microsoft',
                'tipe' => 'Wired Keyboard 600 (USB)',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 15),
            ],
            [
                'no_inventaris' => 'LABKOM/KY/010/' . $tahunSekarang,
                'merk' => 'Digital Alliance',
                'tipe' => 'DA Gaming K1 (Membrane)',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(6, 16),
            ],
        ]);

        // Seeder Penyimpanan (Low-Mid End)
        Penyimpanan::insert([
            [
                'no_inventaris' => 'LABKOM/PM/001/SSD',
                'merk' => 'Kingston',
                'tipe' => 'SSD',
                'kapasitas' => 240, // GB
                'spesifikasi' => 'SATA III, A400 Series',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 25),
            ],
            [
                'no_inventaris' => 'LABKOM/PM/002/HDD',
                'merk' => 'Seagate',
                'tipe' => 'HDD',
                'kapasitas' => 1000, // 1TB
                'spesifikasi' => 'SATA 7200RPM, Barracuda',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 20),
            ],
            [
                'no_inventaris' => 'LABKOM/PM/003/SSD',
                'merk' => 'Western Digital',
                'tipe' => 'SSD',
                'kapasitas' => 480, // GB
                'spesifikasi' => 'SATA III, Green Series',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(7, 18),
            ],
            [
                'no_inventaris' => 'LABKOM/PM/004/HDD',
                'merk' => 'Toshiba',
                'tipe' => 'HDD',
                'kapasitas' => 500, // GB
                'spesifikasi' => 'SATA 7200RPM, P300',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 22),
            ],
            [
                'no_inventaris' => 'LABKOM/PM/005/SSD',
                'merk' => 'Crucial',
                'tipe' => 'SSD',
                'kapasitas' => 256, // GB
                'spesifikasi' => 'NVMe Gen3, P2 Series',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(6, 15),
            ],
            [
                'no_inventaris' => 'LABKOM/PM/006/HDD',
                'merk' => 'Western Digital',
                'tipe' => 'HDD',
                'kapasitas' => 1000, // 1TB
                'spesifikasi' => 'SATA 5400RPM, Blue Series',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 18),
            ],
            [
                'no_inventaris' => 'LABKOM/PM/007/SSD',
                'merk' => 'ADATA',
                'tipe' => 'SSD',
                'kapasitas' => 512, // GB
                'spesifikasi' => 'SATA III, SU650',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(7, 16),
            ],
            [
                'no_inventaris' => 'LABKOM/PM/008/HDD',
                'merk' => 'Seagate',
                'tipe' => 'HDD',
                'kapasitas' => 2000, // 2TB
                'spesifikasi' => 'SATA 5400RPM, SkyHawk Lite (for surveillance, but can be general)',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 12),
            ],
            [
                'no_inventaris' => 'LABKOM/PM/009/SSD',
                'merk' => 'V-Gen',
                'tipe' => 'SSD',
                'kapasitas' => 128, // GB
                'spesifikasi' => 'SATA III, Platinum',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 20),
            ],
            [
                'no_inventaris' => 'LABKOM/PM/010/HDD',
                'merk' => 'Hitachi/HGST', // Often rebranded or older stock
                'tipe' => 'HDD',
                'kapasitas' => 500, // GB
                'spesifikasi' => 'SATA 7200RPM, Travelstar (Laptop HDD can be used in Desktops)',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(6, 14),
            ],
        ]);

        // Seeder Motherboards (Low-Mid End)
        Motherboard::insert([
            [
                'no_inventaris' => 'LABKOM/MB/001/' . $tahunSekarang,
                'merk' => 'ASUS',
                'tipe' => 'PRIME H510M-E',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 15),
            ],
            [
                'no_inventaris' => 'LABKOM/MB/002/' . ($tahunSekarang - 1),
                'merk' => 'MSI',
                'tipe' => 'A320M-A PRO MAX',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 15),
            ],
            [
                'no_inventaris' => 'LABKOM/MB/003/' . ($tahunSekarang - 2),
                'merk' => 'Gigabyte',
                'tipe' => 'GA-H410M H V2',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 18),
            ],
            [
                'no_inventaris' => 'LABKOM/MB/004/' . $tahunSekarang,
                'merk' => 'ASRock',
                'tipe' => 'B450M Steel Legend',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(4, 12),
            ],
            [
                'no_inventaris' => 'LABKOM/MB/005/' . ($tahunSekarang - 1),
                'merk' => 'Biostar',
                'tipe' => 'A520MH',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(6, 16),
            ],
            [
                'no_inventaris' => 'LABKOM/MB/006/' . ($tahunSekarang - 2),
                'merk' => 'ECS', // Elitegroup Computer Systems
                'tipe' => 'H310CH5-M2',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 12),
            ],
            [
                'no_inventaris' => 'LABKOM/MB/007/' . $tahunSekarang,
                'merk' => 'ASUS',
                'tipe' => 'PRIME A320M-K',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(7, 17),
            ],
            [
                'no_inventaris' => 'LABKOM/MB/008/' . ($tahunSekarang - 1),
                'merk' => 'MSI',
                'tipe' => 'H510M PRO-E',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(6, 14),
            ],
            [
                'no_inventaris' => 'LABKOM/MB/009/' . ($tahunSekarang - 2),
                'merk' => 'Gigabyte',
                'tipe' => 'B450M DS3H',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 13),
            ],
            [
                'no_inventaris' => 'LABKOM/MB/010/' . $tahunSekarang,
                'merk' => 'ASRock',
                'tipe' => 'H470M-HDV/M.2',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(4, 10),
            ],
        ]);

        // Seeder DVD (Low-Mid End)
        DVD::insert([
            [
                'no_inventaris' => 'LABKOM/DVD/001/' . $tahunSekarang,
                'dvd' => 'DVD RW',
                'merk' => 'LG',
                'spesifikasi' => 'SATA, 24x Write Speed',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 25),
            ],
            [
                'no_inventaris' => 'LABKOM/DVD/002/' . ($tahunSekarang - 1),
                'dvd' => 'DVD RW',
                'merk' => 'Asus',
                'spesifikasi' => 'SATA, 24x Write Speed, M-DISC Support',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 20),
            ],
            [
                'no_inventaris' => 'LABKOM/DVD/003/' . ($tahunSekarang - 2),
                'dvd' => 'DVD ROM', // ROM lebih jarang, tapi bisa ada
                'merk' => 'Samsung',
                'spesifikasi' => 'SATA, 16x Read Speed',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 15),
            ],
            [
                'no_inventaris' => 'LABKOM/DVD/004/' . $tahunSekarang,
                'dvd' => 'DVD RW',
                'merk' => 'Lite-On',
                'spesifikasi' => 'SATA, 24x Write Speed',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 22),
            ],
            [
                'no_inventaris' => 'LABKOM/DVD/005/' . ($tahunSekarang - 1),
                'dvd' => 'DVD RW External USB', // Eksternal
                'merk' => 'Transcend',
                'spesifikasi' => 'USB 2.0, Slim Portable',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(4, 10),
            ],
            [
                'no_inventaris' => 'LABKOM/DVD/006/' . ($tahunSekarang - 2),
                'dvd' => 'DVD RW',
                'merk' => 'HP',
                'spesifikasi' => 'SATA, 24x Write Speed',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(7, 18),
            ],
            [
                'no_inventaris' => 'LABKOM/DVD/007/' . $tahunSekarang,
                'dvd' => 'DVD RW',
                'merk' => 'Pioneer',
                'spesifikasi' => 'SATA, 24x Write Speed',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(6, 16),
            ],
            [
                'no_inventaris' => 'LABKOM/DVD/008/' . ($tahunSekarang - 1),
                'dvd' => 'DVD RW External USB',
                'merk' => 'LG',
                'spesifikasi' => 'USB 2.0, Slim Portable, M-DISC Support',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(3, 8),
            ],
            [
                'no_inventaris' => 'LABKOM/DVD/009/' . ($tahunSekarang - 2),
                'dvd' => 'DVD RW',
                'merk' => 'Generic OEM', // No brand
                'spesifikasi' => 'SATA, 24x Write Speed',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(15, 30),
            ],
            [
                'no_inventaris' => 'LABKOM/DVD/010/' . $tahunSekarang,
                'dvd' => 'Blu-ray ROM (Internal)', // Satu Blu-ray untuk variasi
                'merk' => 'LG',
                'spesifikasi' => 'SATA, Reads Blu-ray, DVD, CD',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(2, 7),
            ],
        ]);

        // Seeder Mouse (Low-Mid End)
        Mouse::insert([
            [
                'no_inventaris' => 'LABKOM/MOUSE/001/' . $tahunSekarang,
                'merk' => 'Logitech',
                'tipe' => 'M170 (Wireless)',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(15, 35),
            ],
            [
                'no_inventaris' => 'LABKOM/MOUSE/002/' . ($tahunSekarang - 1),
                'merk' => 'HP',
                'tipe' => 'X500 (USB Wired)',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(15, 35),
            ],
            [
                'no_inventaris' => 'LABKOM/MOUSE/003/' . ($tahunSekarang - 2),
                'merk' => 'Dell',
                'tipe' => 'MS116 (USB Wired)',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(12, 30),
            ],
            [
                'no_inventaris' => 'LABKOM/MOUSE/004/' . $tahunSekarang,
                'merk' => 'A4Tech',
                'tipe' => 'OP-620D (USB Wired)',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 28),
            ],
            [
                'no_inventaris' => 'LABKOM/MOUSE/005/' . ($tahunSekarang - 1),
                'merk' => 'Genius',
                'tipe' => 'NX-7000 (Wireless)',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 25),
            ],
            [
                'no_inventaris' => 'LABKOM/MOUSE/006/' . ($tahunSekarang - 2),
                'merk' => 'Logitech',
                'tipe' => 'B100 (USB Wired)',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(20, 40),
            ],
            [
                'no_inventaris' => 'LABKOM/MOUSE/007/' . $tahunSekarang,
                'merk' => 'Fantech',
                'tipe' => 'X5 Zeus (Gaming USB)',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 20),
            ],
            [
                'no_inventaris' => 'LABKOM/MOUSE/008/' . ($tahunSekarang - 1),
                'merk' => 'Rexus',
                'tipe' => 'X1 (Wireless Gaming)',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(7, 18),
            ],
            [
                'no_inventaris' => 'LABKOM/MOUSE/009/' . ($tahunSekarang - 2),
                'merk' => 'Microsoft',
                'tipe' => 'Basic Optical Mouse (USB)',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(10, 22),
            ],
            [
                'no_inventaris' => 'LABKOM/MOUSE/010/' . $tahunSekarang,
                'merk' => 'Lenovo',
                'tipe' => '300 (Wireless Compact)',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(9, 20),
            ],
        ]);

        // Seeder PSU (Low-Mid End)
        PSU::insert([
            [
                'no_inventaris' => 'LABKOM/PSU/001/' . $tahunSekarang,
                'merk' => 'Corsair',
                'tipe' => 'CV450',
                'daya' => 450, // Watt
                'efisiensi' => '80+ Bronze',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 15),
            ],
            [
                'no_inventaris' => 'LABKOM/PSU/002/' . ($tahunSekarang - 1),
                'merk' => 'Cooler Master',
                'tipe' => 'MWE 500 White',
                'daya' => 500,
                'efisiensi' => '80+ White',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(7, 18),
            ],
            [
                'no_inventaris' => 'LABKOM/PSU/003/' . ($tahunSekarang - 2),
                'merk' => 'be quiet!',
                'tipe' => 'System Power 9 400W',
                'daya' => 400,
                'efisiensi' => '80+ Bronze',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(4, 12),
            ],
            [
                'no_inventaris' => 'LABKOM/PSU/004/' . $tahunSekarang,
                'merk' => 'Antec',
                'tipe' => 'Atom V550',
                'daya' => 550,
                'efisiensi' => '80+ (Standard)', // Seringkali tidak ada sertifikasi Bronze/White pada model sangat basic
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(8, 20),
            ],
            [
                'no_inventaris' => 'LABKOM/PSU/005/' . ($tahunSekarang - 1),
                'merk' => 'FSP',
                'tipe' => 'HV PRO 550W',
                'daya' => 550,
                'efisiensi' => '80+ Bronze',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(6, 16),
            ],
            [
                'no_inventaris' => 'LABKOM/PSU/006/' . ($tahunSekarang - 2),
                'merk' => 'Thermaltake',
                'tipe' => 'Litepower 450W',
                'daya' => 450,
                'efisiensi' => '80+ (Standard)',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(9, 22),
            ],
            [
                'no_inventaris' => 'LABKOM/PSU/007/' . $tahunSekarang,
                'merk' => 'EVGA',
                'tipe' => '500 W1',
                'daya' => 500,
                'efisiensi' => '80+ White',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(5, 14),
            ],
            [
                'no_inventaris' => 'LABKOM/PSU/008/' . ($tahunSekarang - 1),
                'merk' => 'Seasonic',
                'tipe' => 'S12III 500',
                'daya' => 500,
                'efisiensi' => '80+ Bronze',
                'tahun' => $tahunSekarang - 1,
                'bulan' => rand(1, 12),
                'stok' => rand(3, 10),
            ],
            [
                'no_inventaris' => 'LABKOM/PSU/009/' . ($tahunSekarang - 2),
                'merk' => 'Deepcool',
                'tipe' => 'DN500',
                'daya' => 500,
                'efisiensi' => '80+ (Standard)',
                'tahun' => $tahunSekarang - 2,
                'bulan' => rand(1, 12),
                'stok' => rand(7, 17),
            ],
            [
                'no_inventaris' => 'LABKOM/PSU/010/' . $tahunSekarang,
                'merk' => 'Aerocool',
                'tipe' => 'United Power 500W',
                'daya' => 500,
                'efisiensi' => '80+ (Standard)',
                'tahun' => $tahunSekarang,
                'bulan' => rand(1, 12),
                'stok' => rand(6, 15),
            ],
        ]);

        User::insert([
            [
                'name' => 'admin',
                'email' => 'admin@mail.com',
                'no_phone' => '081234567890',
                'npp' => 'A11.2022.14079',
                'position' => 'Super Admin',
                'password' => bcrypt('admin'),
            ],
        ]);
    }
}
