<?php

namespace Database\Seeders;

use App\Models\Laboratorium;
use App\Models\SoftwareDetail;
use App\Models\Inventory;
use Illuminate\Database\Seeder;

class LabSoftwareSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * Menambahkan inventaris software ke laboratorium
     * Menggunakan tabel `inventories` dengan relasi polimorfik ke `SoftwareDetail`
     */
    public function run(): void
    {
        // Software dasar untuk semua lab
        $basicSoftware = ['VSCODE', 'CHROME', 'FIREFOX', 'GIT'];

        // Software multimedia/desain
        $multimediaSoftware = [
            'PHOTOSHOP',
            'ILLUSTRATOR',
            'COREL',
            'FIGMA',
            'BLENDER',
            'MAYA',
            '3DSMAX',
            'ANIMATE',
            'AFTEREFFECT',
            'DAVINCI',
            'AUDITION',
        ];

        // Software animasi
        $animasiSoftware = [
            'BLENDER',
            'MAYA',
            '3DSMAX',
            'ZBRUSH',
            'CINEMA4D',
            'TOONBOOM',
            'ANIMATE',
            'CLIPSTUDIO',
            'SPINE',
            'DRAGONBONES',
            'AFTEREFFECT',
            'PHOTOSHOP',
            'ILLUSTRATOR',
        ];

        // Software pemrograman
        $programmingSoftware = [
            'VSCODE',
            'INTELLIJ',
            'ANDROID_STUDIO',
            'XAMPP',
            'NODEJS',
            'LARAGON',
            'MYSQL',
            'DBEAVER',
            'PHPMYADMIN',
            'POSTMAN',
            'GIT',
            'UNITY',
            'GODOT',
        ];

        // Software AI
        $aiSoftware = [
            'PYTHON',
            'JUPYTER',
            'COMFYUI',
            'STABLEDIFF',
            'VSCODE',
            'MYSQL',
            'DBEAVER',
        ];

        // Mapping: lab_ruang => software_array
        $labSoftware = [
            // D2 Labs - Multimedia/DKV/Animasi
            'D2A' => array_merge($basicSoftware, $multimediaSoftware),
            'D2B' => array_merge($basicSoftware, $multimediaSoftware),
            'D2C' => array_merge($basicSoftware, $multimediaSoftware),
            'D2D' => array_merge($basicSoftware, $animasiSoftware),
            'D2E' => array_merge($basicSoftware, $animasiSoftware),
            'D2G' => array_merge($basicSoftware, $multimediaSoftware),
            'D2H' => array_merge($basicSoftware, $multimediaSoftware),
            'D2I' => array_merge($basicSoftware, $multimediaSoftware, $aiSoftware),
            'D2J' => array_merge($basicSoftware, $multimediaSoftware),

            // D3 Labs - Pemrograman
            'D3L' => array_merge($basicSoftware, $programmingSoftware),
            'D3M' => array_merge($basicSoftware, $programmingSoftware),
            'D3N' => array_merge($basicSoftware, $programmingSoftware),
        ];

        $created = 0;
        $skipped = 0;

        foreach ($labSoftware as $labRuang => $softwareCodes) {
            $lab = Laboratorium::where('ruang', $labRuang)
                ->orWhere('ruang', 'LAB ' . $labRuang)
                ->first();

            if (!$lab) {
                $this->command->warn("Lab not found: {$labRuang}");
                $skipped++;
                continue;
            }

            // Remove duplicates
            $softwareCodes = array_unique($softwareCodes);

            $labCreated = 0;
            foreach ($softwareCodes as $code) {
                $software = SoftwareDetail::where('code', $code)->first();
                if (!$software) {
                    continue;
                }

                // Check if inventory already exists for this lab + software
                $exists = Inventory::where('laboratorium_id', $lab->id)
                    ->where('inventoriable_type', SoftwareDetail::class)
                    ->where('inventoriable_id', $software->id)
                    ->exists();

                if ($exists) {
                    continue;
                }

                // Create inventory record (kode_inventaris auto-generated by model)
                Inventory::create([
                    'laboratorium_id' => $lab->id,
                    'inventoriable_type' => SoftwareDetail::class,
                    'inventoriable_id' => $software->id,
                    'nama_barang' => $software->nama, // Add software name
                ]);

                $labCreated++;
                $created++;
            }

            $this->command->info("Created {$labCreated} software inventory for lab: {$labRuang}");
        }

        // Also seed lab_software pivot table for counting purposes
        $this->command->info("Syncing lab_software pivot table...");

        foreach ($labSoftware as $labRuang => $softwareCodes) {
            $lab = Laboratorium::where('ruang', $labRuang)
                ->orWhere('ruang', 'LAB ' . $labRuang)
                ->first();
            if (!$lab)
                continue;

            $softwareCodes = array_unique($softwareCodes);
            $softwareData = [];

            foreach ($softwareCodes as $code) {
                $software = SoftwareDetail::where('code', $code)->first();
                if ($software) {
                    $softwareData[$software->id] = ['version' => $software->versi ?? '1.0'];
                }
            }

            if (!empty($softwareData)) {
                $lab->software()->sync($softwareData);
            }
        }

        $this->command->info("LabSoftware seeder completed: {$created} inventory items created, {$skipped} labs skipped.");
    }
}
