<?php

namespace Database\Seeders;

use App\Models\Laboratorium;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * This seeder creates the super_admin role required for UserSeeder.
     * Other permissions are auto-generated by:
     * - Filament Shield: `php artisan shield:generate --all --panel=admin`
     * - Lab permissions: LabPermissionServiceProvider (creates lab_{slug}_{action} permissions dynamically)
     * 
     * Run this BEFORE UserSeeder.
     */
    public function run(): void
    {
        // Reset cached roles and permissions
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        // Create super_admin role
        $superAdminRole = Role::firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web']);

        // Define generic permissions needed for laboran roles
        $inventoryPermissions = [
            'view_any_software::inventory',
            'view_software::inventory',
            'create_software::inventory',
            'update_software::inventory',
            'delete_software::inventory',
            'delete_any_software::inventory',
            'force_delete_software::inventory',
            'force_delete_any_software::inventory',
            'restore_software::inventory',
            'restore_any_software::inventory',
            'replicate_software::inventory',
            'reorder_software::inventory',
        ];

        $navigationPermissions = [
            'view_any_schedule',
            'view_schedule',
            'view-navigation-item::motherboard',
            'view-navigation-item::processor',
            'view-navigation-item::r::a::m',
            'view-navigation-item::v::g::a',
            'view-navigation-item::penyimpanan',
            'view-navigation-item::d::v::d',
            'view-navigation-item::p::s::u',
            'view-navigation-item::keyboard',
            'view-navigation-item::mouse',
            'view-navigation-item::monitor',
            'view-navigation-item::headphone',
            'view-navigation-item::laboratorium',
            'view-navigation-item::klasifikasi::lab',
            'view-navigation-item::lapor::ptpp',
        ];

        $allLaboranPermissions = array_merge($inventoryPermissions, $navigationPermissions);

        // Ensure all permissions exist
        foreach ($allLaboranPermissions as $permissionName) {
            Permission::firstOrCreate(['name' => $permissionName, 'guard_name' => 'web']);
        }

        // Create lab‑specific roles and assign permissions
        $labs = [
            'd2a' => 'Laboran_D2A',
            'd2b' => 'Laboran_D2B',
            'd2c' => 'Laboran_D2C',
            'd2d' => 'Laboran_D2D',
            'd2e' => 'Laboran_D2E',
            'd2f' => 'Laboran_D2F',
            'd2g' => 'Laboran_D2G',
            'd2h' => 'Laboran_D2H',
            'd2i' => 'Laboran_D2I',
            'd2j' => 'Laboran_D2J',
            'd2k' => 'Laboran_D2K',
            'd3l' => 'Laboran_D3L',
            'd3m' => 'Laboran_D3M',
            'd3n' => 'Laboran_D3N',
        ];

        // Create lab permissions (view, manage, edit, delete) if labs exist
        if (Schema::hasTable('laboratoria') && Laboratorium::count() > 0) {
            $this->createLabPermissions();
        }

        foreach ($labs as $slug => $roleName) {
            $role = Role::firstOrCreate(['name' => $roleName, 'guard_name' => 'web']);
            $role->givePermissionTo($allLaboranPermissions);
            $role->givePermissionTo("lab_{$slug}_view");
        }
                $this->command->info('✅ Roles and permissions created successfully!');
        $this->command->newLine();
        $this->command->info('📌 Next steps:');
        $this->command->info('   1. Run: php artisan db:seed --class=UserSeeder');
        $this->command->info('   2. Run: php artisan shield:generate --all --panel=admin');
        $this->command->info('   3. Configure lab permissions via Filament Shield UI (/admin/shield/roles)');


        $this->command->info('✅ Role super_admin and laboran created successfully!');
        $this->command->newLine();
        $this->command->info('📌 Next steps:');
        $this->command->info('   1. Run: php artisan db:seed --class=UserSeeder');
        $this->command->info('   2. Run: php artisan shield:generate --all --panel=admin');
        $this->command->info('   3. Configure lab permissions via Filament Shield UI (/admin/shield/roles)');
    }

    protected function createLabPermissions(): void
    {
        $labActions = ['view', 'manage', 'edit', 'delete'];

        Laboratorium::orderBy('ruang')->get()->each(function (Laboratorium $lab) use ($labActions) {
            $labSlug = strtolower(str_replace(['LAB ', ' ', '.'], ['', '_', '_'], $lab->ruang));

            foreach ($labActions as $action) {
                Permission::firstOrCreate([
                    'name' => "lab_{$labSlug}_{$action}",
                    'guard_name' => 'web',
                ]);
            }
        });

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }
}
